/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistemas.distribuidos.exclusionmutua;

import com.sistemas.distribuidos.mbcp.UDPClient;
import com.sistemas.distribuidos.mbcp.UDPServer;
import com.sistemas.distribuidos.mbcp.implementacion.Mensaje;
import java.io.IOException;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lomik
 */
public class FrameCentralizado extends javax.swing.JFrame {

    public static final int puertoInicial = 6788;
    private CentralizadoMutex centralizadoMutex;
    private Thread threadReceive;
    private UDPServer udpServer;
    private Mensaje mensajeSeleccionado;

    /**
     * Creates new form FrameCentralizado
     */
    public FrameCentralizado() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboProcesos = new javax.swing.JComboBox<>();
        lblSeleccionarProceso = new javax.swing.JLabel();
        btnLanzar = new javax.swing.JButton();
        lblCuentaBancariaGinna = new javax.swing.JLabel();
        lblCuentaBancariaIsmael = new javax.swing.JLabel();
        lblSaldoGinna = new javax.swing.JLabel();
        lblSaldoGinna1 = new javax.swing.JLabel();
        lblProcesoCoordinador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProcesosActivos = new javax.swing.JList<>();
        btnRegionCriticaGinna = new javax.swing.JButton();
        btnRegionCriticaIsmael = new javax.swing.JButton();
        lblProcesosActivos = new javax.swing.JLabel();
        lblCoordinador = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listColaPeticionesGinna = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listColaPeticionesIsmael = new javax.swing.JList<>();
        lblRegionCriticaGinna = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboProcesos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROCESO 1", "PROCESO 2", "PROCESO 3", "PROCESO 4", "PROCESO 5", "PROCESO 6" }));

        lblSeleccionarProceso.setText("SELECCIONE UN PROCESO");

        btnLanzar.setText("INICIAR");
        btnLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarActionPerformed(evt);
            }
        });

        lblCuentaBancariaGinna.setText("CUENTA BANCARIA GINNA 1416 1485 0804 2019");

        lblCuentaBancariaIsmael.setText("CUENTA BANCARIA ISMAEL 1516 1485 0804 2019");

        lblSaldoGinna.setText("$ 1500.00");

        lblSaldoGinna1.setText("$ 1000.00");

        lblProcesoCoordinador.setText("COORDINADOR");

        jScrollPane1.setViewportView(listProcesosActivos);

        btnRegionCriticaGinna.setText("RETIRAR $1.00");
        btnRegionCriticaGinna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionCriticaGinnaActionPerformed(evt);
            }
        });

        btnRegionCriticaIsmael.setText("RETIRAR $1.00");
        btnRegionCriticaIsmael.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionCriticaIsmaelActionPerformed(evt);
            }
        });

        lblProcesosActivos.setText("PROCESOS ACTIVOS");

        jScrollPane2.setViewportView(listColaPeticionesGinna);

        jScrollPane3.setViewportView(listColaPeticionesIsmael);

        lblRegionCriticaGinna.setText("COLA PETICIONES");

        jLabel1.setText("CTA GINNA");

        jLabel2.setText("CTA ISMAEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProcesosActivos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCuentaBancariaGinna)
                            .addGap(27, 27, 27))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblCuentaBancariaIsmael)
                            .addGap(23, 23, 23)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLanzar)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(lblSaldoGinna1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegionCriticaGinna, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(lblSaldoGinna)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegionCriticaIsmael, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSeleccionarProceso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblProcesoCoordinador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCoordinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegionCriticaGinna)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRegionCriticaGinna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCoordinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProcesoCoordinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeleccionarProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLanzar))
                        .addGap(10, 10, 10)
                        .addComponent(lblCuentaBancariaGinna)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaldoGinna1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegionCriticaGinna))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCuentaBancariaIsmael)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaldoGinna)
                            .addComponent(btnRegionCriticaIsmael))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2))
                        .addGap(35, 35, 35)))
                .addComponent(lblProcesosActivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarActionPerformed
        int procesoSeleccionado = (this.comboProcesos.getSelectedIndex() + 1);
        int puertoProceso = puertoInicial + procesoSeleccionado;
        Proceso proceso = new Proceso(procesoSeleccionado, puertoProceso);
        centralizadoMutex = new CentralizadoMutex(proceso,this.listColaPeticionesGinna,this.listColaPeticionesIsmael);
        try {
            udpServer = new UDPServer(proceso.getPuerto(), this.centralizadoMutex.mensajesRecibidos, this.centralizadoMutex);
        } catch (SocketException ex) {
            Logger.getLogger(FrameCentralizado.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        threadReceive = new Thread(udpServer);
        threadReceive.start();
        // this.lblSeleccionarProceso.setText(this.comboProcesos.getSelectedItem().toString() + " INICIADO EN PUERTO:" + puertoProceso);
        this.btnLanzar.setEnabled(false);
        this.comboProcesos.setEnabled(false);
        this.lblCoordinador.setText(String.format("PROCESO: %s en %s:%s", Integer.toString(this.centralizadoMutex.coordinador.getNumero()), this.centralizadoMutex.coordinador.getDireccion(), Integer.toString(this.centralizadoMutex.coordinador.getPuerto())).toUpperCase());
        this.lblSeleccionarProceso.setText(String.format("PROCESO ACTIVO: %s en %s:%s", Integer.toString(proceso.getNumero()), proceso.getDireccion(), Integer.toString(proceso.getPuerto())).toUpperCase());

        if(!this.centralizadoMutex.proceso.isCoordinador){
            this.listColaPeticionesGinna.setEnabled(false);
            this.listColaPeticionesIsmael.setEnabled(false);
        }
    }//GEN-LAST:event_btnLanzarActionPerformed

    private void btnRegionCriticaIsmaelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionCriticaIsmaelActionPerformed
        // TODO add your handling code here:
       this.centralizadoMutex.enviarMensaje(2);
    }//GEN-LAST:event_btnRegionCriticaIsmaelActionPerformed

    private void btnRegionCriticaGinnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionCriticaGinnaActionPerformed
        // TODO add your handling code here:
        this.centralizadoMutex.enviarMensaje(1);
      
    }//GEN-LAST:event_btnRegionCriticaGinnaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCentralizado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanzar;
    private javax.swing.JButton btnRegionCriticaGinna;
    private javax.swing.JButton btnRegionCriticaIsmael;
    private javax.swing.JComboBox<String> comboProcesos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCoordinador;
    private javax.swing.JLabel lblCuentaBancariaGinna;
    private javax.swing.JLabel lblCuentaBancariaIsmael;
    private javax.swing.JLabel lblProcesoCoordinador;
    private javax.swing.JLabel lblProcesosActivos;
    private javax.swing.JLabel lblRegionCriticaGinna;
    private javax.swing.JLabel lblSaldoGinna;
    private javax.swing.JLabel lblSaldoGinna1;
    private javax.swing.JLabel lblSeleccionarProceso;
    private javax.swing.JList<String> listColaPeticionesGinna;
    private javax.swing.JList<String> listColaPeticionesIsmael;
    private javax.swing.JList<String> listProcesosActivos;
    // End of variables declaration//GEN-END:variables
}
