/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistemas.distribuidos.exclusionmutua;

import com.sistemas.distribuidos.mbcp.UDPClient;
import com.sistemas.distribuidos.mbcp.UDPServer;
import com.sistemas.distribuidos.mbcp.implementacion.Mensaje;
import java.io.IOException;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ginna Monserrat
 */
public class FrameCentralizado extends javax.swing.JFrame {

    public static final int puertoInicial = 6788;
    private CentralizadoMutex centralizadoMutex;
    private Thread threadReceive;
    private UDPServer udpServer;
    private Mensaje mensajeSeleccionado;

    /**
     * Creates new form FrameCentralizado
     */
    public FrameCentralizado() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboProcesos = new javax.swing.JComboBox<>();
        lblSeleccionarProceso = new javax.swing.JLabel();
        btnLanzar = new javax.swing.JButton();
        lblCuentaBancariaGinna = new javax.swing.JLabel();
        lblCuentaBancariaIsmael = new javax.swing.JLabel();
        lblSaldoIsmael = new javax.swing.JLabel();
        lblSaldoGinna = new javax.swing.JLabel();
        lblProcesoCoordinador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProcesosActivos = new javax.swing.JList<>();
        btnRegionCriticaGinna = new javax.swing.JButton();
        btnRegionCriticaIsmael = new javax.swing.JButton();
        lblProcesosActivos = new javax.swing.JLabel();
        lblCoordinador = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listColaPeticionesGinna = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listColaPeticionesIsmael = new javax.swing.JList<>();
        lblRegionCriticaGinna = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBloqueoCtaGinna = new javax.swing.JLabel();
        lblBloqueoCtaIsmael = new javax.swing.JLabel();
        btnMandarMensajeCoordinador = new javax.swing.JButton();
        btnNotificarNuevoCoordinador = new javax.swing.JButton();
        btnTokenGinna = new javax.swing.JButton();
        lblTokenRingGinna = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTokenIsmael = new javax.swing.JButton();
        lblTokenRingIsmael = new javax.swing.JLabel();
        toggleSolicitaGinna = new javax.swing.JToggleButton();
        toggleSolicitaIsmael = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboProcesos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROCESO 1", "PROCESO 2", "PROCESO 3", "PROCESO 4", "PROCESO 5", "PROCESO 6" }));

        lblSeleccionarProceso.setText("SELECCIONE UN PROCESO");

        btnLanzar.setText("INICIAR");
        btnLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarActionPerformed(evt);
            }
        });

        lblCuentaBancariaGinna.setText("CUENTA BANCARIA GINNA 1416 1485 0804 2019");

        lblCuentaBancariaIsmael.setText("CUENTA BANCARIA ISMAEL 1516 1485 0804 2019");

        lblSaldoIsmael.setText("$ ");

        lblSaldoGinna.setText("$ ");

        lblProcesoCoordinador.setText("1.- ALGORITMO COORDINADOR CENTRALIZADO");

        jScrollPane1.setViewportView(listProcesosActivos);

        btnRegionCriticaGinna.setText("RETIRAR $1.00");
        btnRegionCriticaGinna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionCriticaGinnaActionPerformed(evt);
            }
        });

        btnRegionCriticaIsmael.setText("RETIRAR $1.00");
        btnRegionCriticaIsmael.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegionCriticaIsmaelActionPerformed(evt);
            }
        });

        lblProcesosActivos.setText("PROCESOS ACTIVOS");

        jScrollPane2.setViewportView(listColaPeticionesGinna);

        jScrollPane3.setViewportView(listColaPeticionesIsmael);

        lblRegionCriticaGinna.setText("COLA PETICIONES");

        jLabel1.setText("CTA GINNA");

        jLabel2.setText("CTA ISMAEL");

        lblBloqueoCtaGinna.setText("ESTATUS:");

        lblBloqueoCtaIsmael.setText("ESTATUS:");

        btnMandarMensajeCoordinador.setText("PING COORDINADOR");
        btnMandarMensajeCoordinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMandarMensajeCoordinadorActionPerformed(evt);
            }
        });

        btnNotificarNuevoCoordinador.setText("NOTIFICAR COORDINADOR");
        btnNotificarNuevoCoordinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificarNuevoCoordinadorActionPerformed(evt);
            }
        });

        btnTokenGinna.setText("Token Ring Ginna");
        btnTokenGinna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokenGinnaActionPerformed(evt);
            }
        });

        lblTokenRingGinna.setText("Token Ring Ginna");

        jLabel3.setText("2.-ALGORTIMO PARA  ELECCION DE COORDINADOR POR ANILLO");

        jLabel4.setText("3.- Algoritmo Token Ring");

        btnTokenIsmael.setText("Token Ring Ismael");
        btnTokenIsmael.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokenIsmaelActionPerformed(evt);
            }
        });

        lblTokenRingIsmael.setText("Token Ring Ismael");

        toggleSolicitaGinna.setText("SOLICITA");
        toggleSolicitaGinna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleSolicitaGinnaActionPerformed(evt);
            }
        });

        toggleSolicitaIsmael.setText("SOLICITA");
        toggleSolicitaIsmael.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleSolicitaIsmaelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSeleccionarProceso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblProcesoCoordinador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCoordinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegionCriticaGinna)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblCuentaBancariaGinna))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLanzar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCuentaBancariaIsmael)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBloqueoCtaGinna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSaldoIsmael, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegionCriticaIsmael, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblSaldoGinna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnRegionCriticaGinna, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTokenGinna, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toggleSolicitaGinna))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTokenIsmael, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toggleSolicitaIsmael)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblProcesosActivos)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnMandarMensajeCoordinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(405, 405, 405)
                            .addComponent(btnNotificarNuevoCoordinador)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBloqueoCtaIsmael, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(lblTokenRingGinna, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTokenRingIsmael, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRegionCriticaGinna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCoordinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProcesoCoordinador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeleccionarProceso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLanzar))
                        .addGap(10, 10, 10)
                        .addComponent(lblCuentaBancariaGinna)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaldoGinna, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegionCriticaGinna))
                        .addGap(7, 7, 7)
                        .addComponent(lblBloqueoCtaGinna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCuentaBancariaIsmael)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegionCriticaIsmael)
                            .addComponent(lblSaldoIsmael)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnTokenGinna)
                            .addComponent(toggleSolicitaGinna))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTokenIsmael)
                            .addComponent(toggleSolicitaIsmael))
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloqueoCtaIsmael)
                    .addComponent(lblTokenRingGinna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTokenRingIsmael)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lblProcesosActivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMandarMensajeCoordinador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNotificarNuevoCoordinador))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarActionPerformed
        int procesoSeleccionado = (this.comboProcesos.getSelectedIndex() + 1);
        int puertoProceso = puertoInicial + procesoSeleccionado;
        Proceso proceso = new Proceso(procesoSeleccionado, puertoProceso);
        centralizadoMutex = new CentralizadoMutex(proceso, this.listColaPeticionesGinna, this.listColaPeticionesIsmael, this.lblBloqueoCtaGinna, this.lblBloqueoCtaIsmael, this.btnRegionCriticaGinna, this.btnRegionCriticaIsmael, this.lblSaldoGinna, this.lblSaldoIsmael, this.listProcesosActivos, this.lblTokenRingGinna,this.lblTokenRingIsmael, this.btnTokenGinna,this.btnTokenIsmael);
        try {
            udpServer = new UDPServer(proceso.getPuerto(), this.centralizadoMutex.mensajesRecibidos, this.centralizadoMutex);
        } catch (SocketException ex) {
            Logger.getLogger(FrameCentralizado.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        threadReceive = new Thread(udpServer);
        threadReceive.start();
        // this.lblSeleccionarProceso.setText(this.comboProcesos.getSelectedItem().toString() + " INICIADO EN PUERTO:" + puertoProceso);
        this.btnLanzar.setEnabled(false);
        this.comboProcesos.setEnabled(false);
        this.lblCoordinador.setText(String.format("PROCESO: %s en %s:%s", Integer.toString(this.centralizadoMutex.coordinador.getNumero()), this.centralizadoMutex.coordinador.getDireccion(), Integer.toString(this.centralizadoMutex.coordinador.getPuerto())).toUpperCase());
        this.lblSeleccionarProceso.setText(String.format("PROCESO ACTIVO: %s en %s:%s", Integer.toString(proceso.getNumero()), proceso.getDireccion(), Integer.toString(proceso.getPuerto())).toUpperCase());

        if (!this.centralizadoMutex.proceso.isCoordinador) {
            this.listColaPeticionesGinna.setEnabled(false);
            this.listColaPeticionesIsmael.setEnabled(false);
        }
        this.lblSaldoGinna.setText(String.format("Saldo: $%f", centralizadoMutex.saldoGinna));
        this.lblSaldoIsmael.setText(String.format("Saldo: $%f", centralizadoMutex.saldoIsmael));

        for (int i = 0; i < this.comboProcesos.getItemCount(); i++) {
            int ps = (i + 1);
            int port = puertoInicial + ps;

            if (ps != proceso.getNumero()) {
                CoordinadorAnillo.procesos.add(new Proceso(ps, port));
            } else {
                CoordinadorAnillo.procesos.add(proceso);
            }

        }
        CoordinadorAnillo.procesoActual = proceso;
        UtilsAlgoritmos.actualizaListaProcesos(listProcesosActivos, CoordinadorAnillo.procesos);
    }//GEN-LAST:event_btnLanzarActionPerformed

    private void btnRegionCriticaIsmaelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionCriticaIsmaelActionPerformed
        // TODO add your handling code here:
        if (this.centralizadoMutex.isIsTokenRing()) {
            CentralizadoMutex.saldoIsmael--;
            this.lblSaldoIsmael.setText(Double.toString(CentralizadoMutex.saldoIsmael));
        } else {
            this.centralizadoMutex.enviarMensaje(2);
        }
    }//GEN-LAST:event_btnRegionCriticaIsmaelActionPerformed

    private void btnRegionCriticaGinnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegionCriticaGinnaActionPerformed
        // TODO add your handling code here:
        if (this.centralizadoMutex.isIsTokenRing()) {
            CentralizadoMutex.saldoGinna--;
            this.lblSaldoGinna.setText(Double.toString(CentralizadoMutex.saldoGinna));

        } else {
            this.centralizadoMutex.enviarMensaje(1);
        }

    }//GEN-LAST:event_btnRegionCriticaGinnaActionPerformed

    private void btnMandarMensajeCoordinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMandarMensajeCoordinadorActionPerformed
        Mensaje mensaje = new Mensaje();
        mensaje.TIPO_MENSAJE = 3;
        mensaje.setDatos("IsAlive");

        boolean isAlive = CoordinadorAnillo.isALive(centralizadoMutex.coordinador, mensaje);

        if (!isAlive) {
            this.centralizadoMutex.coordinador.setEstatus("DEAD");
            this.centralizadoMutex.coordinador.setIsDead(true);
            CoordinadorAnillo.actualizaEstatus(centralizadoMutex.coordinador);
            this.centralizadoMutex.proceso.setEstatus("PARTICIPANTE");
            mensaje.setDatos(this.centralizadoMutex.proceso.getEstatus());
            mensaje.setK(this.centralizadoMutex.proceso.numero);
            this.centralizadoMutex.recorreAnillo(this.centralizadoMutex.proceso, mensaje);
            JOptionPane.showMessageDialog(this, "DEAD");
        } else {
            JOptionPane.showMessageDialog(this, "OK");
        }
    }//GEN-LAST:event_btnMandarMensajeCoordinadorActionPerformed

    private void btnNotificarNuevoCoordinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificarNuevoCoordinadorActionPerformed
        // TODO add your handling code here:
        CoordinadorAnillo.procesoActual.setEstatus("");
        CoordinadorAnillo.procesoActual.setIsCoordinador(true);

        this.centralizadoMutex.coordinador = CoordinadorAnillo.procesoActual;
        this.centralizadoMutex.proceso = CoordinadorAnillo.procesoActual;
        CoordinadorAnillo.actualizaEstatus(CoordinadorAnillo.procesoActual);
        UtilsAlgoritmos.actualizaListaProcesos(listProcesosActivos, CoordinadorAnillo.procesos);
        Mensaje mensaje = new Mensaje();
        mensaje.TIPO_MENSAJE = 3;
        mensaje.setDatos("COORDINADOR");
        mensaje.setK(centralizadoMutex.proceso.numero);
        this.centralizadoMutex.recorreAnillo(this.centralizadoMutex.proceso, mensaje);

    }//GEN-LAST:event_btnNotificarNuevoCoordinadorActionPerformed

    private void btnTokenGinnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokenGinnaActionPerformed
        // TODO add your handling code here:
        this.btnRegionCriticaGinna.setEnabled(false);
        this.btnTokenGinna.setEnabled(false);
        Mensaje mensaje = new Mensaje();
        mensaje.TIPO_MENSAJE = 4;
        mensaje.setDatos(String.format("GINNA,%f", CentralizadoMutex.saldoGinna));
        this.centralizadoMutex.recorreAnillo(this.centralizadoMutex.proceso, mensaje);

    }//GEN-LAST:event_btnTokenGinnaActionPerformed

    private void btnTokenIsmaelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokenIsmaelActionPerformed
        // TODO add your handling code here:
        this.btnRegionCriticaIsmael.setEnabled(false);
        this.btnTokenIsmael.setEnabled(false);
        Mensaje mensaje = new Mensaje();
        mensaje.TIPO_MENSAJE = 4;
        mensaje.setDatos(String.format("ISMAEL,%f",  CentralizadoMutex.saldoIsmael));
        this.centralizadoMutex.recorreAnillo(this.centralizadoMutex.proceso, mensaje);
    }//GEN-LAST:event_btnTokenIsmaelActionPerformed

    private void toggleSolicitaGinnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleSolicitaGinnaActionPerformed
        // TODO add your handling code here:
        this.centralizadoMutex.solicitaGinna=this.toggleSolicitaGinna.isSelected();
    }//GEN-LAST:event_toggleSolicitaGinnaActionPerformed

    private void toggleSolicitaIsmaelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleSolicitaIsmaelActionPerformed
        // TODO add your handling code here:
          this.centralizadoMutex.solicitaIsmael=this.toggleSolicitaIsmael.isSelected();
    }//GEN-LAST:event_toggleSolicitaIsmaelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCentralizado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanzar;
    private javax.swing.JButton btnMandarMensajeCoordinador;
    private javax.swing.JButton btnNotificarNuevoCoordinador;
    private javax.swing.JButton btnRegionCriticaGinna;
    private javax.swing.JButton btnRegionCriticaIsmael;
    private javax.swing.JButton btnTokenGinna;
    private javax.swing.JButton btnTokenIsmael;
    private javax.swing.JComboBox<String> comboProcesos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBloqueoCtaGinna;
    private javax.swing.JLabel lblBloqueoCtaIsmael;
    private javax.swing.JLabel lblCoordinador;
    private javax.swing.JLabel lblCuentaBancariaGinna;
    private javax.swing.JLabel lblCuentaBancariaIsmael;
    private javax.swing.JLabel lblProcesoCoordinador;
    private javax.swing.JLabel lblProcesosActivos;
    private javax.swing.JLabel lblRegionCriticaGinna;
    private javax.swing.JLabel lblSaldoGinna;
    private javax.swing.JLabel lblSaldoIsmael;
    private javax.swing.JLabel lblSeleccionarProceso;
    private javax.swing.JLabel lblTokenRingGinna;
    private javax.swing.JLabel lblTokenRingIsmael;
    private javax.swing.JList<String> listColaPeticionesGinna;
    private javax.swing.JList<String> listColaPeticionesIsmael;
    private javax.swing.JList<String> listProcesosActivos;
    private javax.swing.JToggleButton toggleSolicitaGinna;
    private javax.swing.JToggleButton toggleSolicitaIsmael;
    // End of variables declaration//GEN-END:variables
}
