/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sistemas.distribuidos.exclusionmutua;

import com.sistemas.distribuidos.mbcp.UDPServer;
import com.sistemas.distribuidos.mbcp.implementacion.Mensaje;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lomik
 */
public class FrameCentralizado extends javax.swing.JFrame {

    private int procesoSeleccionado;
    private final int puertoInicial = 6788;
    private CentralizadoMutex centralizadoMutex;
    private Thread threadReceive;
    private UDPServer udpServer;
    private Mensaje mensajeSeleccionado;
    /**
     * Creates new form FrameCentralizado
     */
    public FrameCentralizado() {
        initComponents();
        centralizadoMutex= new CentralizadoMutex();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboProcesos = new javax.swing.JComboBox<>();
        lblSeleccionarProceso = new javax.swing.JLabel();
        btnLanzar = new javax.swing.JButton();
        lblCuentaBancariaGinna = new javax.swing.JLabel();
        lblCuentaBancariaIsmael = new javax.swing.JLabel();
        lblSaldoGinna = new javax.swing.JLabel();
        lblSaldoGinna1 = new javax.swing.JLabel();
        lblProcesoCoordinador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboProcesos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROCESO 1", "PROCESO 2", "PROCESO 3", "PROCESO 4", "PROCESO 5", "PROCESO 6" }));

        lblSeleccionarProceso.setText("SELECCIONE UN PROCESO");

        btnLanzar.setText("INICIAR");
        btnLanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLanzarActionPerformed(evt);
            }
        });

        lblCuentaBancariaGinna.setText("CUENTA BANCARIA GINNA 1416 1485 0804 2019");

        lblCuentaBancariaIsmael.setText("CUENTA BANCARIA ISMAEL 1516 1485 0804 2019");

        lblSaldoGinna.setText("$ 1500.00");

        lblSaldoGinna1.setText("$ 1000.00");

        lblProcesoCoordinador.setText("PROCESO COORDINADOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSeleccionarProceso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboProcesos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLanzar)
                        .addGap(58, 58, 58)
                        .addComponent(lblProcesoCoordinador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCuentaBancariaGinna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSaldoGinna))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCuentaBancariaIsmael)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaldoGinna1)))
                .addGap(0, 196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSeleccionarProceso)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProcesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLanzar)
                    .addComponent(lblProcesoCoordinador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuentaBancariaGinna)
                    .addComponent(lblSaldoGinna))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaldoGinna1)
                    .addComponent(lblCuentaBancariaIsmael))
                .addContainerGap(360, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLanzarActionPerformed
        procesoSeleccionado = (this.comboProcesos.getSelectedIndex() + 1);
        int puertoProceso = puertoInicial + (procesoSeleccionado);
        try {
            udpServer = new UDPServer(puertoProceso, this.centralizadoMutex.mensajesRecibidos, this.centralizadoMutex,false);
        } catch (SocketException ex) {
            Logger.getLogger(FrameCentralizado.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
        threadReceive = new Thread(udpServer);
        threadReceive.start();
        this.lblSeleccionarProceso.setText(this.comboProcesos.getSelectedItem().toString() + " INICIADO EN PUERTO:" + puertoProceso);
        this.btnLanzar.setEnabled(false);
        this.comboProcesos.setEnabled(false);
    }//GEN-LAST:event_btnLanzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCentralizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCentralizado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLanzar;
    private javax.swing.JComboBox<String> comboProcesos;
    private javax.swing.JLabel lblCuentaBancariaGinna;
    private javax.swing.JLabel lblCuentaBancariaIsmael;
    private javax.swing.JLabel lblProcesoCoordinador;
    private javax.swing.JLabel lblSaldoGinna;
    private javax.swing.JLabel lblSaldoGinna1;
    private javax.swing.JLabel lblSeleccionarProceso;
    // End of variables declaration//GEN-END:variables
}
